### ISSUE TITLE
Please add the Pages feature Pagination 

### ISSUE THREAD

**Issue by eArabic** [zlaxy/phpcsvguestbook#1]
Hello
Thank you very much for this excellent script and great idea.
An important feature to add to this script is to show the number of pages so that for example each page has 10 entries.
thank you very much
Sorry for the mistakes I do not know English well

![pag](https://user-images.githubusercontent.com/24383546/30794275-e8b39b72-a1cf-11e7-8425-8ca93a206821.png)

**Comment by zlaxy** [comment]
Hello. Done, pagination feature was added.
[https://github.com/zlaxy/phpcsvguestbook/commit/31003891fa866bea16b5765b6216ee04164033f0](url)

Change `$GBpagination` variable in `settings.php` for editing count of entries on one page.

![2017-09-25-123151_1280x800_scrot](https://user-images.githubusercontent.com/19224533/30802466-527861a4-a1ef-11e7-8a4a-574bf90e986c.png)

**Comment by eArabic** [comment]
Thank you so much very excellent work.
It is now very cool, it is a very excellent script.
Thank you very much my dear friend

**Comment by eArabic** [comment]
Hello
There is a simple problem that  (your name:) field does not appear.
**Please also add a search feature.**
Please solve this problem and thank you very much.
And again you me:
Thank you very much my dear friend

![4](https://user-images.githubusercontent.com/24383546/30822410-5f31b1d8-a231-11e7-8102-e8c7c043ff1c.png)
![5](https://user-images.githubusercontent.com/24383546/30822411-5f37c2bc-a231-11e7-83d7-f1456443383b.png)

**Comment by eArabic** [comment]
How pagination feature was added administration.php
**Please also add a search feature**
Thank you very much my dear friend

**Comment by zlaxy** [comment]
>  There is a simple problem that (your name:) field does not appear.

Fixed in new version.

> How pagination feature was added administration.php

Added.

> Please also add a search feature.

Do you mean to add text search bar on guest and admin pages?

**Comment by eArabic** [comment]
Dear Friend
Thank you so much for the update.
Yes on  add text search bar on guest and admin pages
Thank you very much for quick response and updates.

**Comment by eArabic** [comment]
Hello
There is a slight error in entering the name as a link, see the image to see the problem more.

![1](https://user-images.githubusercontent.com/24383546/30844407-8f03262e-a297-11e7-98f5-5d21648c5b71.png)
![2](https://user-images.githubusercontent.com/24383546/30844408-8f05d04a-a297-11e7-8ee4-01c5a18fb859.png)
![3](https://user-images.githubusercontent.com/24383546/30844409-8f07d62e-a297-11e7-9b42-519f68acd7bf.png)

**Comment by zlaxy** [comment]
> see the image to see the problem more.

This bug was fixed just now...
Now i am thinking about compact search algorithm. Don't want to use external modules and librares for that.

**Comment by eArabic** [comment]
Hello
**Thank you very much** for the update, can you add more read so that the full text does not appear but only shows a specific number of words so that the settings are controlled.
How to add read more  , limit text length   **'Read more'** link
Can you add the Disable **option captcha settings**
I regret the many questions

![11](https://user-images.githubusercontent.com/24383546/30871066-521f98a8-a2ee-11e7-9b14-d719c0ed2b73.png)

**Comment by zlaxy** [comment]
Hello again, you can check search feature. I'll make configurable captcha and add 'read more' feature, but i don't want to use javascript in this project, i'll make it with reloading page.

**Comment by eArabic** [comment]
Thanks very much, update is very important
Very cool work became script with very excellent search feature
Feature : captcha 
Pretty shaped numbers do not have a problem but I see that the settings have the option to disable them or activate them, And the choice of how many numbers.
Thank you so much my dear friend

**I suggest opening** another project the same as this project but a simple forum so that classifications and other forum matters such as this project are added: MicroTXT
A tiny textboard   , no database required.
https://github.com/beardog108/MicroTXT

**Comment by zlaxy** [comment]
'Read more' feature was added.
Ability to disable captcha also was added. I don't recommend you to use this script (or similar) without captcha - it will be vulnerable for spammer-bots.

Also, before i used simple captcha with simple addition of 2 numbers - but spambots attacked it. Now every number in captcha has 3 digits, one of them is hidden (you can check it in sources), more than year this method is secure on few sites.

> I suggest opening another project the same as this project but a simple forum

You can fork this repository and change it as you wish (just change name or localization, for example) - licence of this project does not put any restrictions on changing, editing and using original project.

**Comment by eArabic** [comment]
Hello dear friend
Thanks so much for the updates
Please add the **Attach Files** or **Image feature**
And add a picture show feature with text.
Specifying the types of images and files allowed **from the settings**, as well as the size of the file.
thank you very much

**Comment by zlaxy** [comment]
I added attach image feature with last commit. Only images could be uploaded, maximum size is configurable.

**Comment by zlaxy** [comment]
I see you forked this project, please, make pull request with your settings_ar.php

**Comment by eArabic** [comment]
Hello dear friend
Thank you very much for updating to the Add Picture feature.
**Please add a new Subject Title field.**
And add a new **field to the subject classification** (category) of the message
is added to its options and labels ...
Did you have the option to sort messages by city and label so that text for a specific city or category appears, added to the Advanced Search feature.
And make after adding a message that returns **to the homepage automatically.**
And thank you very much, wonderful script and excellent best script I loved it so much.

![3](https://user-images.githubusercontent.com/24383546/30954253-22cb8512-a438-11e7-9864-bef0f7833b90.png)

**Comment by eArabic** [comment]
Hello dear friend
Can add feature:
**Reply to** participation and message from visitors.
And not only the validity of the manager.
As well as feature:
**Lock & Sticky message :**
**Locked message**  cannot be replied to.
**Sticky message** remain at the top of home page.
thank you very much

**Comment by zlaxy** [comment]
Hello, i added subject and categories fields. Also you can enable or disable 'city' and 'homepage' fields in settings.php

I will think about sorting, replying, lock and sticky messages later.

To make replying, i will need to make a lot of changes, it's easier, probably, to write the whole program again.

**Comment by eArabic** [comment]
Thank you so much my dear friend
You are a very professional, very wonderful and excellent work, thank you so much.
Thanks for the new updates.
I am waiting for any updates from you.

**Comment by eArabic** [comment]
Hello dear friend
An error occurred when you click Page : Last
Fatal error: Call to undefined function intdiv() in /Data/phpcsvguestbook-master/index.php on line 225

![3](https://user-images.githubusercontent.com/24383546/31012222-ab335af6-a519-11e7-9c57-e2f814c46238.png)

**Comment by zlaxy** [comment]
> Call to undefined function intdiv()

intdiv() is php7 function, changed it to php5-compatible (int)() in last pull request.

eArabic, please show me template with correct arab marking (from right to left), i'll make setting for right-to-left / left-to-right orientation of main controls.

**Comment by eArabic** [comment]
Dear Friend
Thank you so much for the update.
We are a beginner and new in programming, PHP and CSS
I will try adjusting the rtl.css settings to suit the Arabic language.
Thank you for helping to update this great and excellent script.

**Comment by eArabic** [comment]
Hello dear friend
Look at this simple site test
http://arabic.freecluster.eu/index.html
http://earabic.iblogger.org/index.html
Click: LIVE DEMO
Arabic is showing well Used:

```
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
```
**These: http://materializecss.com/getting-started.html**

With some minor modifications to suit the Arabic language.

**Comment by eArabic** [comment]
Hello dear friend
There is a simple error forwarding link

![aa](https://user-images.githubusercontent.com/24383546/31045708-2bb70c26-a5f2-11e7-961d-3c09206d9363.png)

**Comment by eArabic** [comment]
**Hello dear friend**
The script is very excellent and daily it becomes better and better than before.

**Please add the Attach Files feature like:**
Pdf, Doc, Docx, Xls, Xlsx, Txt, Zip, Rar and more.
Where I can control the files **from the settings**.

**Is it possible to add an image if it is a link or a code?**
If an image link is inserted in the message
You want to show the image within the text

![33](https://user-images.githubusercontent.com/24383546/31046186-1da64eb6-a5fd-11e7-8791-7e3d361b20d4.png)


Have you found a solution to replying by visitors and Sticky message.
**You can add a comment on messages, which is the same idea of replying to messages.**

Can I add this feature to protect my username and not use it from others?
There is no need to "register", just enter the same name @ password of your choice every time, or leave blank for anonymous post. Your password will be displayed encrypted and hashed to visitors for security reasons!

![0100](https://user-images.githubusercontent.com/24383546/31046195-39d06d42-a5fd-11e7-9e25-208fbc0111c6.png)


They are located in: flatboard test:
http://flatboard.free.fr/view.php/forum/announcements

There is also a nice idea to enter, participate and register at: NoNonsenseForum
https://github.com/Kroc/NoNonsenseForum
Here's the test:
http://forum.camendesign.com/

**Comment by zlaxy** [comment]
Hello, you can check replies.
Lock & Sticky, Sorting, file attaching and other features will be implemented later.

> Look at this simple site test

Nice pages, good design.

> There is a simple error forwarding link

If you didn't type 'http://', your browser add current host to prefix of this link. I'll try to fix it later.

> Is it possible to add an image if it is a link or a code?

If you set '$GBstriptags=false;' in settings.php - you could use simple html tags `<img src="link">` in messages.

> Can I add this feature to protect my username and not use it from others?

It will be better to set sticky and locked posts in admin page.

**Comment by eArabic** [comment]
Hello dear friend
I thank you for the update and for adding the feature: replies
**Me some notes:**
Can I add to the settings option to disable the appearance of replies.
When you reply to a message that shows the reply as a message, is there a way to distinguish the replies,
There is no way that appears in the previous message.
**The Reply to Messages feature in administration : Response**
Very good if this feature is opened to everyone because the replies appear with the message better and more beautiful.
If this option is opened for everyone, customize the name of the user who replies.

![888](https://user-images.githubusercontent.com/24383546/31049196-d1c03aae-a636-11e7-8b06-5e7425606a90.png)

**Comment by eArabic** [comment]
Hello
You told me to show the picture did not appear, what is the reason:

![999](https://user-images.githubusercontent.com/24383546/31049257-2e3b574a-a638-11e7-9c5b-f29e5f9a7dab.png)

![10](https://user-images.githubusercontent.com/24383546/31049261-36c9fb3c-a638-11e7-8f41-beffe0776c10.png)

**Comment by zlaxy** [comment]
Hello, you can check 'category search' (just click on search bar text field) and adding links without http.
Also, i make redesign of gbdb.csv (added few new fields), old versions of gbdb.csv could work not fine with last versions of script. I recommend make new gbdb.csv....ah...i see tehere is broken order of entries now. I'll fix it today later.

>  You told me to show the picture did not appear, what is the reason:

Check your settings.php, this string:
$GBstriptags=false; // enable or disable strip tags function during adding new entry

**Comment by zlaxy** [comment]
> I'll fix it today later.

Fixed.

Anyway, you must update your gbdb.csv. DB-file from old versions could work wrong

**Comment by eArabic** [comment]
Hello dear friend
Thank you for the new update.
I will test, thank you very much.
Please add a very simple editor like the attached picture.
Wait for you: Sticky message is very important.
As well as:
Attached Files feature like:
Pdf, Doc, Docx, Xls, Xlsx, Txt, Zip, Rar and more.
Where I can control the files from the settings

![a](https://user-images.githubusercontent.com/24383546/31056468-bfa907a2-a6da-11e7-81aa-3cbac91b327a.png)


I'm not a programming expert but a newbie I learn.
**I hope you open the same project** running on databases would be an excellent project.
So it is simple and fast, and it has most of the features required to share and write topics.
I hope you do a project like this and learn about the database.

**Comment by zlaxy** [comment]
> Wait for you: Sticky message is very important.

Done. You can check it.

> Look at this simple site test
> http://arabic.freecluster.eu/index.html
> http://earabic.iblogger.org/index.html

Could i add one of this pages to readme sample? Which of this 2 hosts are better for that (which is stable hosting of them)?

> Where I can control the files from the settings.

What control do you want? List of allowed file name extensions? Or something other?

>  Please add a very simple editor like the attached picture.

I'll check later what editor is better for this project (licensing and compatibility).

> I hope you open the same project running on databases would be an excellent project.

There are many guestbook projects with mysql databases. I don't think that we need one more.

**Comment by eArabic** [comment]
Hello dear friend
Thank you so much
I am registered in this free hosting: https://infinityfree.net/
As well: http://www.ultimatefreehost.in/
All good and I tried infinityfree and found it good and tried it it's free.

**Comment by eArabic** [comment]
This account is ready for you:
Code Encrypted Text :
.
.
.

http://ivan.my-board.org/?do=decrypt
http://zlaxy.freecluster.eu/?do=decrypt

**Comment by eArabic** [comment]
Thank you so much my dear friend
The new feature Sticky message works perfectly.

**Comment by eArabic** [comment]
Dear Friend
Please add hidden fields that are shown when needed from the settings
Such as Field 1, Field 2, and Field 3 are controlled from the settings and labeled change as well.
Please make the YouTube clip link appear in the message. 
I tried to show the image link and clip link so far I have not succeeded so can you make it easier.
You have enabled the option from the settings: $ GBstriptags
Thanks so much for the updates

**Comment by zlaxy** [comment]
Salut,  eArabic, i have no such time from now, i'll try to implement your new ideas in the coming weeks.

> Password 1: 123456789

Please change this passwords, i just add links to this example pages in readme in coming version.

**Comment by eArabic** [comment]
Dear Friend
Thank you so much
As well please add
Attached Files feature like:
Pdf, Doc, Docx, Xls, Xlsx, Txt, Zip, Rar and more.
Where I can control the files from the settings.

**Comment by zlaxy** [comment]
eArabic, hello. You can test attached files and 3 new special fields.

Please, make pull request to this repository with you settings_ar.php

**Comment by eArabic** [comment]
Hello dear friend
Thank you very much for the new updates
I will test it

**Comment by eArabic** [comment]
Hello dear friend
You can add reading from more than one database gbdb.csv with that customized through the settings.
Add a field that has a unique AutoNumber for each message so that it's easy to access and control the field from the settings.
Please add an option in the default language selection settings.
I have a question outside how can I add the Pages feature Pagination from a text file.

```
<html>
<body>
<?php
$file = "text.txt";
$myfile = fopen("$file", "r") or die("Unable to open file!");
// Output one line until end-of-file
while(!feof($myfile)) {
  echo fgets($myfile) . "<br>";
}
fclose($myfile);
?>
</body>
</html>

```

**Comment by eArabic** [comment]
Hello dear friend
Can I add the option to disable email from settings.

**Comment by eArabic** [comment]
Hello dear friend
When you reply to the message, you can make it add an automatic message subject instead of writing a new subject .
Now, when you reply to any message, you must fill in all the data, including the subject of the message, even if the subject of the message you want to reply to is automatically written, allowing the change of address if necessary.

**Comment by zlaxy** [comment]
Salut!

> Can I add the option to disable email from settings.

Done

>  You can add reading from more than one database gbdb.csv with that customized through the settings.

What settings you want to will be customized?

> Add a field that has a unique AutoNumber for each message so that it's easy to access and control the field from the settings.

You can use sixth column from CSV for this purposes. This number is unix time stamp of message.
You can convert this timestamp to date with function: `date("j.m.Y, H:i",$Entry[5]);`

> Please add an option in the default language selection settings.

Do you want to add ability for choosing localization by user?

> I have a question outside how can I add the Pages feature Pagination from a text file.

If you don't want to make your own function ( https://stackoverflow.com/a/3707457/6224462 ), you can use third-party script like this: https://github.com/jasongrimes/php-paginator

> When you reply to the message, you can make it add an automatic message subject instead of writing a new subject .

I added inherit of message field during reply.



Also, i added your settings_ar.php to this project. Is it possible to translate comments to arabic like comments transleted there: https://github.com/zlaxy/phpcsvguestbook/blob/master/settings_ru.php ?

**Comment by eArabic** [comment]
Thank you so much my dear friend
I was traveling on vacation now I entered the Internet, and apologize for the late reply.

I hope to read the wonderful script more than a database such as:
gbdb.csv, gbdb1.csv, and gbdb2 .csv
The purpose of this process is to allocate the size of each database, for example 250 megabytes.
If the size of the database increases, I think that browsing and searching will become slow, or if it has nothing to do with it, I do not know what you think.

 I do not know what the size of the csv database is so that browsing and search is slow and weak.

**Can I add the option to read database data from another server?**

For language selection, I mean a choice of settings:

`$ lang = 'ar';  // Default language ('ar' and other from 'settings_ar.php')
`
Thank you very much dear friend for every update.

**Comment by zlaxy** [comment]
> For language selection, I mean a choice of settings:

Done, see $GBlanguage variable.

> Can I add the option to read database data from another server?

If you need just read database, you can use direct http (https, ftp etc) link for $GBdata variable. For example:
`$GBdata="https://zlaxyi.soundragon.su/gb/gbdb.csv";`
But if you need write to CSV file on another server - it's more difficult, and protocol specified.

> The purpose of this process is to allocate the size of each database, for example 250 megabytes.

I doubt that guestbook database could increase to 250MB (if spambots will attack it?), but later i think about implementation division of CSV file by size.

**Comment by zlaxy** [comment]
Hello, eArabic.
I want ask your help for this project: https://github.com/zlaxy/aeiou
Could you please record for me simple words for every letter of arabic alphabet? I need it in audio and in text. Each letter should have at least two examples. If that letter can be read differently, please show it in different examples. Please use the shortest words you can find. Like English and Russian alphabets there: https://oss-it.ru/share/aeiou/
I am ready to pay some money for your help.
Greetings,
Ivan.

**Comment by eArabic** [comment]
Hello dear friend Ivan
Thank you very much, I am ready to help, but this needs some time just give me some time.
I will try to find you audio clips for Arabic characters with examples.
I am pleased to help you.
I do not want money, you are my dear friend.
I hope you will give me some time.
I will be collecting audio files and images for Arabic characters.
With Regards

**Comment by zlaxy** [comment]
@eArabic hello friend, i made little additions to this project: now it could be simple used not only as guestbook, but also as feedback form.
I'll close this issue. There many issues in one...If you will have any requests or find some errors, please make a separate issue for each of them.

Thank you for you contribution to this project!
