### ISSUE TITLE
Please Add Simple Login System

### ISSUE THREAD

**Issue by eArabic** [zlaxy/phpcsvguestbook#2]
Hello dear friend
Is it possible to add a simple login system feature?
With some features and features and control of the settings.
for example:
The feature of adding a topic should be registered? This can be disabled from the settings.
Reply feature should be registered? This can be disabled from the settings.
User Role feature.
Add a database backup feature with export and import.

**Comment by eArabic** [comment]
Hello dear friend
Can I add a share link feature to each post to send to friends?
Adding a link feature to a separate page for each post when clicking on the post opens on another full page.
Thank you very much my dear friend

**Comment by zlaxy** [comment]
Hello, friend. I'll try to implement your ideas after NewYear, now i don't have such time for it.

**Comment by zlaxy** [comment]
Hello, friend. I added share link feature: https://github.com/zlaxy/phpcsvguestbook/commit/deaad1cd5b25e798d0e179e3154b8ea27d100a32
You can find share link on date of post.

**Comment by zlaxy** [comment]
Also, i think about 'login system' feature... Where to store passwords and usernames in this case? With this feature it will be not simple guestbook, but something more. It seems to me that such a functional will be redundant for this project.

If you really need this, you can choose for this another project (for example, some forum). This feature will have to be rewritten base part in this project, it's easier to start a new project (or fork it, if you like idea to store open data in csv file).

Are you think out what you can add and improve in this project, or do you really need this feature?

**Comment by zlaxy** [comment]
>  Add a database backup feature with export and import.

Backup/Export: you can simple download ../gbdb.csv ($GBdata variable).
Import: just overwrite it.

**Comment by eArabic** [comment]
**Hello dear friend**
Thank you so much for the update.
**Thank you for this wonderful update.**
Login System is not very necessary.
If added easy is good.
User names can be save in a text file as follows:
admin = admin     And so on ...
Username = Password
This project is very excellent.
It is like a forum  light and fast is used in the responses, support and topics ...
**Thank you so much**

**Comment by zlaxy** [comment]
Than i will close this issue too...If there is a system of logins - this is no longer be a guest book. Guest - means access to records for any person without registration.
